[project]
name = "data-analysis"
version = "0.1.0"
authors = [
    {name = "Youngheon Kim", email = "heons38@naver.com"}
]
description = "타이타닉 데이터셋 분석 과제"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.10"
